var eventType = {
    Request: 0,
    ContentRequested: 1,
    ContentReady: 2,
    PlayStarted: 3,
    PlayCompleted: 4,
    AdClicked: 5,
    RatingSubmitted: 6,
    ClickThrougUrlAccessed: 7,
    Error: 16,
    Impression: 17,
    CreativeView: 18,
    Midpoint: 19,
    FirstQuartile: 20,
    ThirdQuartile: 21,
    Mute: 22,
    Unmute: 23,
    Pause: 24,
    Resume: 25,
    AdVideoFirstQuartile: 112,
    AdVideoMidpoint: 113,
    AdVideoThirdQuartile: 114
};
